name: Java Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Run Tests on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run tests
        run: mvn clean install || (echo "Build or tests failed!" && exit 1) 
